name: ci 
on:
  push:
    branches:
      - main
      - alex_patch 
      - abhi_patch
    workflow_dispatch:
      - main
      - alex_patch
      - abhi_patch
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git rm -r --cached .
          rm -rf docs/news
          git config --global user.email "am2455@njit.edu"
          git config --global user.name "absrocks"
          git submodule add https://github.com/arcs-njit-edu/news.git docs/news
          git submodule update --init --recursive
          git commit -m "Add submodule"
          git push
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material pandas tabulate markdown-exec mkdocstrings mkdocs-table-reader-plugin mkdocs-awesome-pages-plugin mkdocs-autolinks-plugin
      - run: mkdocs gh-deploy --force
